(deftheme my-adwaita-dark
  "Created 2024-12-20.")

(custom-theme-set-variables
 'my-adwaita-dark
 '(frame-background-mode ''dark))

(custom-theme-set-faces
 'my-adwaita-dark
 '(ansi-color-black ((t (:background "#1E1E1E" :foreground "#1E1E1E"))))
 '(ansi-color-blue ((t (:background "#12488B" :foreground "#12488B"))))
 '(ansi-color-bright-black ((t (:background "#5D5D5D" :foreground "#5D5D5D"))))
 '(ansi-color-bright-blue ((t (:background "#2A7BDE" :foreground "#2A7BDE"))))
 '(ansi-color-bright-cyan ((t (:background "#33C7DE" :foreground "#33C7DE"))))
 '(ansi-color-bright-green ((t (:background "#33D17A" :foreground "#33D17A"))))
 '(ansi-color-bright-magenta ((t (:background "#C061CB" :foreground "#C061CB"))))
 '(ansi-color-bright-red ((t (:background "#F66151" :foreground "#F66151"))))
 '(ansi-color-bright-yellow ((t (:background "#E9AD0C" :foreground "#E9AD0C"))))
 '(ansi-color-cyan ((t (:background "#2AA1B3" :foreground "#2AA1B3"))))
 '(ansi-color-green ((t (:background "#26A269" :foreground "#26A269"))))
 '(ansi-color-magenta ((t (:background "#A347BA" :foreground "#A347BA"))))
 '(ansi-color-red ((t (:background "#C01C28" :foreground "#C01C28"))))
 '(ansi-color-white ((t (:background "#CFCFCF" :foreground "#CFCFCF"))))
 '(ansi-color-yellow ((t (:background "#A2734C" :foreground "#A2734C"))))
 '(compilation-mode-line-fail ((t (:inherit compilation-error :weight bold))))
 '(cursor ((t (:background "#77767B"))))
 '(diff-added ((t (:foreground "#26A1A2"))))
 '(diff-changed ((t (:foreground "#E66100"))))
 '(diff-error ((t (:inherit error))))
 '(diff-file-header ((t (:weight bold))))
 '(diff-header ((t (:foreground "#4E57BA"))))
 '(diff-hunk-header ((t (:foreground "#D38B09"))))
 '(diff-indicator-added ((t (:inherit diff-added))))
 '(diff-indicator-changed ((t (:inherit diff-changed))))
 '(diff-indicator-removed ((t (:inherit diff-removed))))
 '(diff-refine-added ((t (:weight bold))))
 '(diff-refine-changed ((t (:weight bold))))
 '(diff-refine-removed ((t (:inherit diff-refine-changed :weight bold))))
 '(diff-removed ((t (:foreground "#F66151"))))
 '(doom-modeline-bar-inactive ((t (:background "#DEDDDA"))))
 '(elisp-shorthand-font-lock-face ((t (:inherit font-lock-keyword-face))))
 '(error ((t (:foreground "#C01C28" :weight bold))))
 '(flymake-error ((t (:underline (:color "#C01C28" :style wave :position nil)))))
 '(flymake-warning ((t (:underline (:color "#F5C211" :style wave :position nil)))))
 '(font-lock-builtin-face ((t (:foreground "#1C71D8"))))
 '(font-lock-comment-face ((t (:foreground "#77767B"))))
 '(font-lock-constant-face ((t (:foreground "#4E57BA"))))
 '(font-lock-function-call-face ((t (:foreground "#1C71D8"))))
 '(font-lock-function-name-face ((t (:foreground "#1C71D8" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#C64600" :weight bold))))
 '(font-lock-number-face ((t (:foreground "#4e57ba"))))
 '(font-lock-preprocessor-face ((t (:foreground "#C64600"))))
 '(font-lock-string-face ((t (:foreground "#218787"))))
 '(font-lock-type-face ((t (:foreground "#218787" :weight bold))))
 '(font-lock-variable-name-face ((t nil)))
 '(fringe ((t nil)))
 '(header-line ((t (:inherit variable-pitch :background "#F1F1F1" :box (:line-width (4 . 4) :color "#F1F1F1" :style flat-button)))))
 '(header-line-highlight ((t :box (:color "#504E55"))))
 '(highlight ((t (:background "#F6F5F4"))))
 '(hl-line ((t (:inherit (highlight default) :extend t))))
 '(isearch ((t (:background "#3584e4" :foreground "#ffffff"))))
 '(keycast-key ((t)))
 '(lazy-highlight ((t (:background "#F9F06B" :distant-foreground "black"))))
 '(line-number ((t (:inherit (shadow default)))))
 '(line-number-current-line ((t (:inherit (hl-line line-number) :weight bold))))
 '(link ((t (:foreground "#3584e4" :underline t))))
 '(link-visited ((t (:inherit link :foreground "#813D9C"))))
 '(markdown-header-face ((t (:foreground "#218787" :weight bold))))
 '(markdown-list-face ((t (:foreground "#C64600" :weight bold))))
 '(minibuffer-prompt ((t (:inherit default :weight bold))))
 '(mode-line ((t :box (:line-width 6 :color "grey75" :style nil))))
 '(mode-line-active ((t :box (:line-width 6 :color "grey75" :style nil))))
 '(mode-line-highlight ((t (:foreground "#9a9996"))))
 '(mode-line-inactive ((t :box (:line-width 6 :color "grey90" :style nil))))
 '(orderless-match-face-0 ((t (:foreground "#8939A4"))))
 '(orderless-match-face-1 ((t (:inherit orderless-match-face-0))))
 '(orderless-match-face-2 ((t (:inherit orderless-match-face-0))))
 '(orderless-match-face-3 ((t (:inherit orderless-match-face-2))))
 '(org-mode-line-clock-overrun ((t (:inherit error))))
 '(region ((t (:extend t :background "#DEC6E6"))))
 '(tab-line-tab ((t)))
 '(tab-line-tab-active ((t)))
 '(tab-line-tab-inactive ((t)))
 '(trailing-whitespace ((t (:foreground "#B0AFAC"))))
 '(vertical-border ((t nil)))
 '(vertico-current ((t (:inherit hl-line :extend t :weight bold))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 98 :width normal :foundry "ADBO" :family "Source Code Pro")))))

(provide-theme 'my-adwaita-dark)
